name: pull-request

on: [pull_request, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: npm install
      - run: npm run lint
      - run: npm run check-types
      - run: npm run build
